services:
  - docker

cache: ccache

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
  - tools/start_ccache
  - docker build --network ccache_network --build-arg MAKEFLAGS=-j2 -t p4lang-third-party .
