#!/bin/bash
THIRD_PARTY_IMAGE=${1:-p4lang/third-party:latest}

EXIT_STATUS=0
function test_python_import() {
  echo "- Checking 'import $1'..."
  docker run $THIRD_PARTY_IMAGE python -c "import $1"
  if [ $? -eq 0 ]; then
    echo "  - PASS"
  else
    echo "  - FAIL"
    EXIT_STATUS=1
  fi
}

echo "--> docker run $THIRD_PARTY_IMAGE cat $HOME/.bashrc:"
docker run $THIRD_PARTY_IMAGE bash -c 'cat $HOME/.bashrc'
echo "--> docker run $THIRD_PARTY_IMAGE printenv:"
docker run $THIRD_PARTY_IMAGE printenv | sort
echo "--> docker run $THIRD_PARTY_IMAGE which uv"
docker run $THIRD_PARTY_IMAGE which uv

SAVE=$PWD
for j in $(docker run $THIRD_PARTY_IMAGE find / -name site-packages 2>/dev/null)
do
    echo "--> run_tests site-packages ----------------------------------------------------------------------"
    echo $j
    docker run $THIRD_PARTY_IMAGE find $j | egrep '(scapy|ptf|nnpy|thrift)'
done
for j in $(docker run $THIRD_PARTY_IMAGE find / -name dist-packages 2>/dev/null)
do
    echo "--> run_tests dist-packages ----------------------------------------------------------------------"
    echo $j
    docker run $THIRD_PARTY_IMAGE find $j | egrep '(scapy|ptf|nnpy|thrift)'
done
cd $SAVE

test_python_import "thrift"

exit $EXIT_STATUS
